/**
 * The PayPal and Crypto buttons shown beside Buy Me a Coffee in every README.
 * Every README points at this repository on raw.githubusercontent.com, so there is
 * one copy to regenerate instead of one per repository.
 *
 * They are generated to match the vendor's button-buy-me-a-coffee.svg: the same
 * 841.9x245.3 canvas, the same 38.2 corner and the same inner 460x120 design grid
 * (scaled by 1.830217 and centred), because the README renders the row at one
 * fixed width and a box a few units off makes the row wobble.
 *
 * Each button wears its brand colour. The app shows the brand only on hover, which
 * a README cannot do: GitHub strips <style> and script, an inline style has no
 * pseudo-classes, and an SVG embedded as <img> never sees the pointer. A flat brand
 * fill also reads in both GitHub themes without a <picture>, which GitHub's
 * sanitiser breaks inside a link.
 *
 * The README points at the PNG, so the lettering does not depend on the fonts of
 * the viewer's renderer.
 *
 * Run: node buttons/gen-buttons.mjs
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { execSync } from "node:child_process";

const require = createRequire(import.meta.url);
const { Resvg } = require(`${execSync("npm root -g").toString().trim()}/@resvg/resvg-js`);

const __dir = dirname(fileURLToPath(import.meta.url));

/** The shared canvas, taken from the vendor button so the row lines up. */
const W = 841.9;
const H = 245.3;
const R = 38.2;
/** button-docs.svg's own transform: a 460x120 design centred in that canvas. */
const SCALE = 1.830217;
const DX = 0.05;
const DY = 12.85;

/**
 * Simple Icons paths in a 24x24 box, from the same sources as the app's marks.
 *
 * A mark may give its own ink box, `[x, y, w, h]` inside that square. The two
 * brand logos fill the square and give none; the Bitcoin letterform does not, and
 * laid out as if it did it would float in a coin-sized hole.
 */
const MARK_PAYPAL =
  "M15.607 4.653H8.941L6.645 19.251H1.82L4.862 0h7.995c3.754 0 6.375 2.294 6.473 5.513-.648-.478-2.105-.86-3.722-.86m6.57 5.546c0 3.41-3.01 6.853-6.958 6.853h-2.493L11.595 24H6.74l1.845-11.538h3.592c4.208 0 7.346-3.634 7.153-6.949a5.24 5.24 0 0 1 2.848 4.686M9.653 5.546h6.408c.907 0 1.942.222 2.363.541-.195 2.741-2.655 5.483-6.441 5.483H8.714Z";
/**
 * Bitcoin's letterform without the coin. The logo is one path, a disc with the
 * symbol wound against it, so dropping the first subpath leaves the letter filled
 * and its counters open. The leading move is absolute because the original was
 * relative to the disc.
 *
 * With dark ink on the orange fill the disc would be a dark circle, which at README
 * size reads as a dot rather than a symbol; the app's crypto button drops it for
 * the same reason. The ink box is measured from the path's cubic extrema.
 */
const MARK_BITCOIN = {
  d: "M17.288 10.291c.24-1.59-.974-2.45-2.64-3.03l.54-2.153-1.315-.33-.525 2.107c-.345-.087-.705-.167-1.064-.25l.526-2.127-1.32-.33-.54 2.165c-.285-.067-.565-.132-.84-.2l-1.815-.45-.35 1.407s.975.225.955.236c.535.136.63.486.615.766l-1.477 5.92c-.075.166-.24.406-.614.314.015.02-.96-.24-.96-.24l-.66 1.51 1.71.426.93.242-.54 2.19 1.32.327.54-2.17c.36.1.705.19 1.05.273l-.51 2.154 1.32.33.545-2.19c2.24.427 3.93.257 4.64-1.774.57-1.637-.03-2.58-1.217-3.196.854-.193 1.5-.76 1.68-1.93h.01zm-3.01 4.22c-.404 1.64-3.157.75-4.05.53l.72-2.9c.896.23 3.757.67 3.33 2.37zm.41-4.24c-.37 1.49-2.662.735-3.405.55l.654-2.64c.744.18 3.137.524 2.75 2.084v.006z",
  ink: [5.804, 4.178, 11.514, 15.2],
};

/** The inner design grid, in the 460x120 space button-docs.svg also uses. */
const MARK = 52;   // mark edge, in the 460x120 design grid
const GAP = 24;    // between mark and word
const FONT = 'Verdana, DejaVu Sans, Arial, sans-serif';
const SIZE = 46;

/**
 * One button. Mark and word are centred as one block: set from the left, they leave
 * empty fill on the right, and beside the vendor button, whose lettering fills its
 * box, the row reads as three different sizes. `startX` comes from the measured
 * width in `textWidth`.
 */
function button({ fill, ink, mark, label }, startX) {
  const { d, box } = markGeometry(mark);
  const textX = startX + box.w + GAP;
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">
  <!-- Generated by gen-donate-buttons.mjs - do not hand-edit. Same box, same
       corner and the same inner 460x120 grid as button-docs.svg, so the README
       row lines up at width="220". -->
  <rect x="0" y="0" width="${W}" height="${H}" rx="${R}" ry="${R}" fill="${fill}"/>
  <g transform="translate(${DX},${DY}) scale(${SCALE})">
    <g transform="translate(${startX + box.dx},${34 + box.dy}) scale(${box.scale})" fill="${ink}">
      <path d="${d}"/>
    </g>
    <text x="${textX}" y="60" fill="${ink}" font-family="${FONT}"
          font-size="${SIZE}" font-weight="700" dominant-baseline="central">${label}</text>
  </g>
</svg>
`;
}

/**
 * A mark's drawn size and position in the 460x120 design grid. The mark is scaled
 * to the row's mark height and keeps its aspect, so a narrow letterform stands as
 * tall as a round logo. A plain path string counts as a full-bleed 24-square.
 */
function markGeometry(mark) {
  const d = typeof mark === "string" ? mark : mark.d;
  const [x, y, w, h] = typeof mark === "string" ? [0, 0, 24, 24] : mark.ink;
  const scale = MARK / h;
  return { d, box: { w: w * scale, dx: -x * scale, dy: -y * scale, scale } };
}

/**
 * The word's painted width, from the renderer's own bounding box. An estimated
 * advance width for a bold face can be a few percent off, which only shows once
 * the three buttons sit side by side.
 */
function textWidth(label) {
  const probe = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 200" width="900" height="200">
    <text x="10" y="100" fill="#000" font-family="${FONT}" font-size="${SIZE}"
          font-weight="700" dominant-baseline="central">${label}</text>
  </svg>`;
  const bbox = new Resvg(probe, { fitTo: { mode: "width", value: 900 } }).getBBox();
  return Math.round(bbox.width);
}

const BUTTONS = [
  // PayPal's own dark blue, white ink. Measured 13.4:1, the same pairing the
  // app's own hover uses for this brand.
  { name: "button-paypal", fill: "#003087", ink: "#ffffff", mark: MARK_PAYPAL, label: "PayPal" },
  // Bitcoin's orange stands for the whole window, as it does on the
  // app's own crypto button: it is the one symbol that reads as "crypto" to
  // somebody who has never held any. Dark ink on it, 7.9:1.
  { name: "button-crypto", fill: "#f7931a", ink: "#161616", mark: MARK_BITCOIN, label: "Crypto" },
];

for (const b of BUTTONS) {
  const tw = textWidth(b.label);
  const startX = Math.round((460 - (markGeometry(b.mark).box.w + GAP + tw)) / 2);
  const svg = button(b, startX);
  writeFileSync(join(__dir, `${b.name}.svg`), svg, "utf8");
  const png = new Resvg(svg, { fitTo: { mode: "width", value: Math.round(W) } })
    .render()
    .asPng();
  writeFileSync(join(__dir, `${b.name}.png`), png);
  console.log(`${b.name}: Wort ${tw}px breit, Block startet bei x=${startX}`);
}
